# Generated by Django 4.1 on 2022-08-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ONLINE_SERVICES', 'ONLINE_SERVICES'), ('OTHERS', 'OTHERS'), ('RENT', 'RENT'), ('FOOD', 'FOOD'), ('TRAVEL', 'TRAVEL')], max_length=255),
        ),
    ]
